### ISSUE TITLE
Design and architecture discussion

### ISSUE THREAD

**Issue by ghost** [airavata-courses/Squadron#1]
As discussed in our meeting last week, please do research and provide your solution here for the architecture of authentication module.
Questions to be answered are:
1. What kind of authentication should we use?
2. Which MQ should be used?
3. How will the API Gateway communicate with the micro-services?
4. Functionality and different methods that we will need in the 'user-authentication' and 'session management' microservices.
5. How will the data flow from the user interface -> api gw -> micro-services ---> user interface again?

**Comment by aarushiibisht** [comment]
1. What kind of authentication should we use?

User Management service could implement 2 approaches. 1) User signs up using a unique username(can be email address), password and other details like first name, last name etc. 
This information is saved in a SQL database. We could use some encryption for storing the password.
2) We give the user another option ie to sign up using google. This approach will follow the standard   Authorization Code Grant oauth flow. For this user, our database will store the username and other details like first name, last name but not the password. 

My suggestion is to create a User table that holds all the details and also a column which keeps a track of the method used by the user to sign up eg google/direct.
For simplicity, we could implement only one approach for now.

2. Which MQ should be used?
We could use either a messaging queue or a pub-sub model. The difference between the 2 is that in a messaging queue implementation one message can be consumed by only one process and in case of a pub/sub approach multiple processes can consume a single message. To read more about it refer to this article https://streaml.io/resources/tutorials/concepts/messaging-and-queuing. RabbitMQ is a MQ implementation and Kalfa is a pub/sub implementation. My suggestion is to use pub/sub approach because all user activities need to be logged in the session management service and user activity in one microservice might need to send a message to another microservice. If MQ approach is used each activity will have to send 2 messages ie one to the session management queue and another to the other microservice queue. In order to learn something new, we can try using Redis for a pub/sub implementation. For more info refer https://redis.io/topics/pubsub

**Comment by aarushiibisht** [comment]
3. How will the API Gateway communicate with the micro-services?

The question here is to decide on the API protocol. We could use gRPC or thrift instead of REST. Both of them are language agnostic and lot of boilerplate code is auto-generated.

**Comment by akhil-8607** [comment]
1. If we go for Authorization Code Grant oauth flow , most of the the standard options available like google login require our web pages to be https which in-turn requires SSL certificate .They refuse simple http connection .For our application so It would be better to go for standard username and password approach .

**Comment by akhil-8607** [comment]
2. If we go for OAuth based approach it might better approach proceed with  Rabit MQ due to the need of the SSL certificate due to as it's required for that approach but Kaftka is better for handling Big data loads which might be the requirement of our application in the future when scaling the application .

If we go for username / password based approach other approaches like other MQ based approaches and pub-sub based approaches  might be the best ways.

Redis Pub/Sub is not very good for handing Big data

**Comment by aarushiibisht** [comment]
There are 2 options for the weather application:

1) Plotting precipitation, storm prediction by taking  Nexrad data from AWS. Data retrieval service will pull the data from Amazon s3 bucket on receiving a user request. The following information will be required to make a call to the bucket.

- Site is the NEXRAD ground station (map of ground stations)

- Volume_Number is the volume id number (cycles from 0 to 999)

- YYYYMMDD is the date of the volume scan

- HHMMSS is the time of the volume scan

- CHUNKNUM is the chunk number

- CHUNKTYPE is the chunk type  

The data received will be  bzip2 compressed, will need to be decompressed. 
(https://docs.opendata.aws/noaa-nexrad/readme.html)

2) Plotting temperature, precipitation, pressure, wind speed, clouds using data from https://openweathermap.org/weathermap. All of the data here is not free. But it offers limited data for free customers and limited number of API calls can be made per second. I do not think it will be a problem for us. They provide APIs and be queried on the basis of city name/ city id/ latitude longitude. There are many other options, more info can be found here https://openweathermap.org/current. APIs will return JSON which can then be forwarded to other microservice for generating the plots.

**Comment by ghost** [comment]
API design pattern: 
https://microservices.io/patterns/apigateway.html

**Comment by ghost** [comment]
![Ass_1](https://user-images.githubusercontent.com/5948157/74493670-c5773000-4ef8-11ea-9ce3-2fdfcb36ad85.jpg)
