### ISSUE TITLE
Model Execution Service Implementation

### ISSUE THREAD

**Issue by aarushiibisht** [airavata-courses/Squadron#4]

**Comment by akhil-8607** [comment]
Data is obtained from the data retrieval Microservice through rest communication is in json format. 

For the data source we have decided the data sent from the data retrieval Microservice contains data like zip code , month name , temperature data  etc.. 

Cost of water : The most reliable source for the cost of water is found to be https://www.circleofblue.org/waterpricing/. 

The average cost per month  turned out to be 35$ per house using for every 50 gallon per person per day usage considering a family of four lives in every house on average. 

The simplified calculation of water that can be obtained from the roof assuming 90% efficiency of water that can be collected (Gallons )  is = Area (in sqft ) * rain fall in inches * 0.56 

cost that can be saved = (35 / 4 x 50(200)) * (no of persons * usage in gallons per person per day )*(water that can be collected (obtained from above equation )) 

https://greywateraction.org/faq/how-much-rain-can-i-collect-from-my-roof/

**Comment by ghost** [comment]
-http://www.harvesth2o.com/Is_RWH_a_good_investment.shtml

-TAMU university resource
https://rainwaterharvesting.tamu.edu/catchment-area/

-https://www.energy.gov/eere/femp/water-efficient-technology-opportunity-rainwater-harvesting-systems

**Comment by aarushiibisht** [comment]
Implementation has been completed therefore closing this issue
